- name: Provision Grafana
  block:
    - name: "Log into OpenShift as admin"
      k8s_auth:
        username: "{{ ocp_admin }}"
        password: "{{ ocp_admin_pwd }}"
      register: k8s_auth_results

    - name: Clone Grafana git repo
      git:
        repo: "{{ grafana_operator_git_repo }}"
        version: "{{ grafana_operator_git_tag }}"
        dest: "{{ grafana_operator_local_dir }}"

    - name: Install Grafana Operator CRDs
      block:
        - include: ../../common/runOcShell.yml
          vars:
            oc_command: "oc create -f {{ grafana_operator_local_dir }}/deploy/crds -n {{ proj_nm_demo }}"
      rescue:
        - include: ../../common/runOcShell.yml
          vars:
            oc_command: "oc replace -f {{ grafana_operator_local_dir }}/deploy/crds -n {{ proj_nm_demo }}"

    - name: Install Grafana Operator Roles
      block:
        - include: ../../common/runOcShell.yml
          vars:
            oc_command: "oc create -f {{ grafana_operator_local_dir }}/deploy/roles -n {{ proj_nm_demo }}"
      rescue:
        - include: ../../common/runOcShell.yml
          vars:
            oc_command: "oc replace -f {{ grafana_operator_local_dir }}/deploy/roles -n {{ proj_nm_demo }}"

    - name: Install Grafana Cluster Roles
      block:
        - include: ../../common/runOcShell.yml
          vars:
            oc_command: "oc create -f {{ grafana_operator_local_dir }}/deploy/cluster_roles"
      rescue:
        - include: ../../common/runOcShell.yml
          vars:
            oc_command: "oc replace -f {{ grafana_operator_local_dir }}/deploy/cluster_roles"

    - name: Install Grafana Operator
      block:
        - include: ../../common/runOcShell.yml
          vars:
            oc_command: "oc create -f {{ grafana_operator_local_dir }}/deploy/operator.yaml -n {{ proj_nm_demo }}"
      rescue:
        - include: ../../common/runOcShell.yml
          vars:
            oc_command: "oc replace -f {{ grafana_operator_local_dir }}/deploy/operator.yaml -n {{ proj_nm_demo }}"

    - name: Log out of OpenShift admin user
      when: k8s_auth_results.k8s_auth.api_key is defined
      k8s_auth:
        state: absent
        api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
    
    - name: "Log into OpenShift as project user"
      k8s_auth:
        username: "{{ ocp_proj_user }}"
        password: "{{ ocp_proj_user_pwd }}"
      register: k8s_auth_results

    - name: Wait for Grafana Operator to spin up
      k8s_info:
        api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
        namespace: "{{ proj_nm_demo }}"
        api_version: apps/v1
        kind: Deployment
        name: grafana-operator
      register: grafana_operator_deployment
      until: grafana_operator_deployment.resources is defined and grafana_operator_deployment.resources|length == 1 and grafana_operator_deployment.resources[0].status.readyReplicas is defined and grafana_operator_deployment.resources[0].status.readyReplicas == 1 and grafana_operator_deployment.resources[0].status.availableReplicas is defined and grafana_operator_deployment.resources[0].status.availableReplicas == 1
      retries: 50
      delay: 10

    - name: Check if Grafana is already deployed
      k8s_info:
        api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
        api_version: v1
        kind: Service
        namespace: "{{ proj_nm_demo }}"
        name: grafana-service
      register: grafana_svc

    - name: Deploy Grafana Data Source
      k8s:
        api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
        namespace: "{{ proj_nm_demo }}"
        definition: "{{ lookup('template', '../objects/grafana-datasource.yml') }}"
      when: grafana_svc.resources|length == 0

    - name: "Deploy Grafana Dashboard"
      k8s:
        api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
        namespace: "{{ proj_nm_demo }}"
        definition: "{{ lookup('file', '../objects/grafana-dashboard-' + item + '.yml') }}"
      when: grafana_svc.resources|length == 0
      loop: "{{ grafana_dashboards }}"

    - name: Deploy Grafana
      k8s:
        api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
        namespace: "{{ proj_nm_demo }}"
        definition: "{{ lookup('file', '../objects/grafana.yml') }}"
      when: grafana_svc.resources|length == 0

  always:
    - name: If OpenShift login succeeded try to log out
      when: k8s_auth_results.k8s_auth.api_key is defined
      k8s_auth:
        state: absent
        api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"

    - name: Delete Grafana git repo
      file:
        state: absent
        path: "{{ grafana_operator_local_dir }}"
