- hosts: localhost
  gather_facts: no
  module_defaults:
    group/k8s:
      host: "{{ ocp_api_url }}"
      validate_certs: no
    group/uri:
      validate_certs: no
  vars:
    ocp_admin: opentlc-mgr
  roles:
    - Operators
    - Demo
