apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: additional-scrape-configs
data:
  prometheus-additional.yml: "{{ lookup('file', './roles/Prometheus/objects/additional-scrape-configs-data.txt') | b64encode }}"
