apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: container-security-operator
  namespace: "{{ proj_nm_rh_operators }}"
spec:
  channel: alpha
  name: container-security-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic
