apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: prometheus-datasource
  namespace: "{{ proj_nm_demo }}"
  labels:
    app.kubernetes.io/part-of: grafana
spec:
  name: Prometheus
  datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://prometheus:9090
      isDefault: true
      editable: true
      jsonData:
        tlsSkipVerify: true
        timeInterval: "5s"
