apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: grafana
  labels:
    app: grafana
    app.kubernetes.io/part-of: grafana
  annotations:
    app.openshift.io/connects-to: prometheus
spec:
  ingress:
    enabled: true
    labels:
      app: grafana
      app.kubernetes.io/part-of: grafana
    annotations:
      app.openshift.io/connects-to: prometheus
  service:
    labels:
      app: grafana
      app.kubernetes.io/part-of: grafana
    annotations:
      app.openshift.io/connects-to: prometheus
  deployment:
    labels:
      app: grafana
      app.kubernetes.io/part-of: grafana
    annotations:
      app.openshift.io/connects-to: prometheus
  config:
    auth:
      disable_signout_menu: true
      disable_login_form: false
    auth.anonymous:
      enabled: true
    log:
      level: warn
      mode: console
    security:
      admin_password: admin
      admin_user: admin
  dashboardLabelSelector:
    - matchExpressions:
        - key: grafana-dashboard-for
          operator: In
          values:
            - spring-music-cdc
