- name: Check if application is already deployed
  k8s_info:
    api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
    api_version: apps.openshift.io/v1
    kind: DeploymentConfig
    namespace: "{{ proj_nm_demo }}"
    name: spring-music
  register: spring_music_dc

- name: Deploy application if needed
  k8s:
    api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
    namespace: "{{ proj_nm_demo }}"
    definition: "{{ lookup('template', '../objects/app.yml') }}"
  when: spring_music_dc.resources|length == 0